/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Esfera;

/**
 *
 * @author SMOUANA
 */
public class DistanciaEsferica_A_B extends javax.swing.JInternalFrame {
    double R = 6371;
    
    /**
     * Creates new form DistanciaEsferica_A_B
     */
    public DistanciaEsferica_A_B() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblResultados = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblLatMinutos1 = new javax.swing.JTextField();
        lblLogGraus1 = new javax.swing.JTextField();
        lblLatSegundos1 = new javax.swing.JTextField();
        lblLatGraus1 = new javax.swing.JTextField();
        lblLogMinutos1 = new javax.swing.JTextField();
        lblLogSegundos1 = new javax.swing.JTextField();
        bCalcular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jlabel2 = new javax.swing.JLabel();
        lblLogMinutos2 = new javax.swing.JTextField();
        lblLogSegundos2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblLatMinutos2 = new javax.swing.JTextField();
        lblLogGraus2 = new javax.swing.JTextField();
        lblLatSegundos2 = new javax.swing.JTextField();
        lblLatGraus2 = new javax.swing.JTextField();
        bApagar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setTitle("Distancia Esferica");
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblResultados.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabel4.setText("Latitude");

        lblLatMinutos1.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        lblLatMinutos1.setText("59");

        lblLogGraus1.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        lblLogGraus1.setText("28");

        lblLatSegundos1.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        lblLatSegundos1.setText("20.06");

        lblLatGraus1.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        lblLatGraus1.setText("25");
        lblLatGraus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblLatGraus1ActionPerformed(evt);
            }
        });

        lblLogMinutos1.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        lblLogMinutos1.setText("8");
        lblLogMinutos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblLogMinutos1ActionPerformed(evt);
            }
        });

        lblLogSegundos1.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        lblLogSegundos1.setText("23.31");
        lblLogSegundos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblLogSegundos1ActionPerformed(evt);
            }
        });

        bCalcular.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        bCalcular.setText("Calcular");
        bCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCalcularActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabel1.setText("Longitude");

        jlabel2.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jlabel2.setText("Distancia Esferica em Km :");

        lblLogMinutos2.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        lblLogMinutos2.setText("12");
        lblLogMinutos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblLogMinutos2ActionPerformed(evt);
            }
        });

        lblLogSegundos2.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        lblLogSegundos2.setText("32.49");

        jLabel8.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabel8.setText("Longitude");

        jLabel9.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabel9.setText("Latitude");

        lblLatMinutos2.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        lblLatMinutos2.setText("36");

        lblLogGraus2.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        lblLogGraus2.setText("77");

        lblLatSegundos2.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        lblLatSegundos2.setText("50.12");

        lblLatGraus2.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        lblLatGraus2.setText("28");
        lblLatGraus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblLatGraus2ActionPerformed(evt);
            }
        });

        bApagar.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        bApagar.setText("Apagar");
        bApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bApagarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabel11.setText("Coordenadas do Ponto 1");

        jLabel12.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabel12.setText("Coordenadas do Ponto 2");

        jLabel13.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabel13.setText("G");

        jLabel14.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabel14.setText("M");

        jLabel15.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabel15.setText("S");

        jLabel16.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabel16.setText("S");

        jLabel17.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabel17.setText("M");

        jLabel18.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabel18.setText("G");

        jLabel19.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabel19.setText("S");

        jLabel20.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabel20.setText("M");

        jLabel21.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabel21.setText("G");

        jLabel22.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabel22.setText("G");

        jLabel23.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabel23.setText("M");

        jLabel24.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabel24.setText("S");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLogGraus1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLatGraus1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblLogMinutos1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLatMinutos1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel17)
                            .addComponent(jLabel14)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLogGraus2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(lblLatGraus2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel22)))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLatMinutos2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLogMinutos2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlabel2)
                                .addGap(46, 46, 46)
                                .addComponent(lblResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bCalcular)
                                .addGap(116, 116, 116)
                                .addComponent(bApagar)
                                .addGap(70, 70, 70)))
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLatSegundos1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLatSegundos2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLogSegundos2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel24)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLogSegundos1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)))
                        .addGap(105, 105, 105))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLatGraus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel4))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLogGraus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLatMinutos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLogMinutos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17))))
                        .addGap(59, 59, 59)
                        .addComponent(jLabel12)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblLatGraus2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                    .addComponent(jLabel21))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLogGraus2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel8)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(lblLatMinutos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLogMinutos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(lblLogSegundos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(183, 183, 183))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addGap(166, 166, 166)
                            .addComponent(jLabel19)
                            .addGap(40, 40, 40)
                            .addComponent(jLabel24))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblLatSegundos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(154, 154, 154)
                            .addComponent(lblLatSegundos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(lblLogSegundos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCalcular)
                    .addComponent(bApagar))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLatGraus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblLatGraus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLatGraus1ActionPerformed

    private void lblLogMinutos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblLogMinutos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLogMinutos1ActionPerformed

    private void lblLogMinutos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblLogMinutos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLogMinutos2ActionPerformed

    private void lblLatGraus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblLatGraus2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLatGraus2ActionPerformed

    private void bCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCalcularActionPerformed
// Entrada da Longitude e Latitude

double lat1Decimal = Double.parseDouble(lblLatGraus1.getText()) + Double.parseDouble(lblLatMinutos1.getText())/60 + Double.parseDouble(lblLatSegundos1.getText())/3600;
double lat2Decimal = Double.parseDouble(lblLatGraus2.getText()) + Double.parseDouble(lblLatMinutos2.getText())/60 + Double.parseDouble(lblLatSegundos2.getText())/3600;

double log1Decimal = Double.parseDouble(lblLogGraus1.getText()) + Double.parseDouble(lblLogMinutos1.getText())/60 + Double.parseDouble(lblLogSegundos1.getText())/3600;
double log2Decimal = Double.parseDouble(lblLogGraus2.getText()) + Double.parseDouble(lblLogMinutos2.getText())/60 + Double.parseDouble(lblLogSegundos2.getText())/3600;

//Formulas para calcular (cos, Sin, tan) dos pontos
        double sin1 = -1*Math.sin(Math.PI/180 * lat1Decimal);
        //            lblResultadosLat1.setText(String.valueOf(sin1));
                    
         double cos1 = Math.cos(Math.PI/180 * lat1Decimal);
         //           lblResultadosLog1.setText(String.valueOf(cos1));
                    
         double sin2 = Math.sin(Math.PI/180 * lat2Decimal);
         //           lblResultadosLat2.setText(String.valueOf(sin2));
                    
         double cos2 = Math.cos(Math.PI/180 * lat2Decimal);
           //         lblResultadosLog2.setText(String.valueOf(cos2));
                              
    //Calculo da Diferenca de longitudes         
        double deltaLog = log2Decimal - log1Decimal;
     
        double cosDeltaLog = Math.cos(Math.PI/180 * deltaLog);
    //    lblResultadosLat1.setText(String.valueOf(cosDeltaLog));
        
        double sinDeltaLog = Math.sin(Math.PI/180 * deltaLog); 
    //    lblResultadosLat2.setText(String.valueOf(sinDeltaLog));
    // Calculo do (d) em Radianos
        double d = Math.acos( sin1 * sin2 + cos1 * cos2 * cosDeltaLog);
    //    lblResultadosLat1.setText(String.valueOf(d));
    //Formula para calcular Distancia Esferica
       double D = R * d;             
           lblResultados.setText(String.valueOf(D));
                    
    }//GEN-LAST:event_bCalcularActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formAncestorAdded

    private void lblLogSegundos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblLogSegundos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLogSegundos1ActionPerformed

    private void bApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bApagarActionPerformed
                // bOTAO PARA APAGAR OS CAMPOS
            this.lblLatGraus1.setText(null);
            this.lblLatMinutos1.setText(null);
            this.lblLatSegundos1.setText(null);
             this.lblLatGraus2.setText(null);
            this.lblLatMinutos2.setText(null);
            this.lblLatSegundos2.setText(null);
            this.lblLogGraus1.setText(null);
            this.lblLogMinutos1.setText(null);
            this.lblLogSegundos1.setText(null);
             this.lblLogGraus2.setText(null);
            this.lblLogMinutos2.setText(null);
            this.lblLogSegundos2.setText(null);
            this.lblResultados.setText(null);
    
    }//GEN-LAST:event_bApagarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bApagar;
    private javax.swing.JButton bCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JTextField lblLatGraus1;
    private javax.swing.JTextField lblLatGraus2;
    private javax.swing.JTextField lblLatMinutos1;
    private javax.swing.JTextField lblLatMinutos2;
    private javax.swing.JTextField lblLatSegundos1;
    private javax.swing.JTextField lblLatSegundos2;
    private javax.swing.JTextField lblLogGraus1;
    private javax.swing.JTextField lblLogGraus2;
    private javax.swing.JTextField lblLogMinutos1;
    private javax.swing.JTextField lblLogMinutos2;
    private javax.swing.JTextField lblLogSegundos1;
    private javax.swing.JTextField lblLogSegundos2;
    private javax.swing.JLabel lblResultados;
    // End of variables declaration//GEN-END:variables
}
