/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Esfera;

import Elipsoide.Achatamento;
import Elipsoide.Excentricidade;
import Elipsoide.GrandeNormal;
import Elipsoide.PequenaNormal;
import Elipsoide.RaioMedio;
import Elipsoide.SeccaoMeridiana;
import Elipsoide.Semi_Eixos_Maior;
import Elipsoide.Semi_Eixos_Menor;
import javax.swing.JOptionPane;

/**
 *
 * @author SMOUANA
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTP = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        jMenuEsfera = new javax.swing.JMenu();
        jRaioDoParalelo = new javax.swing.JMenuItem();
        jDistanciaEsferica = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuEsfericasCartesianas = new javax.swing.JMenuItem();
        jVelocidadeDeRotacao = new javax.swing.JMenuItem();
        jMenuAchatamento = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuExcentricidade = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuGrandeNormal = new javax.swing.JMenuItem();
        jMenuPequenaNormal = new javax.swing.JMenuItem();
        jMenuSeccaoMeridiana = new javax.swing.JMenuItem();
        jMenuRaioMedio = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        lblEixoMaior = new javax.swing.JMenuItem();
        lblEixoMenor = new javax.swing.JMenuItem();
        sair = new javax.swing.JMenu();
        lblSair = new javax.swing.JMenuItem();
        sobre = new javax.swing.JMenu();
        jSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela principal");

        jTP.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTPAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jTPLayout = new javax.swing.GroupLayout(jTP);
        jTP.setLayout(jTPLayout);
        jTPLayout.setHorizontalGroup(
            jTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jTPLayout.setVerticalGroup(
            jTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        jLabel1.setText("Calculadora Geodesica");

        jLabel2.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabel2.setText("Desenvolvido por:");

        jLabel3.setFont(new java.awt.Font("Garamond", 3, 14)); // NOI18N
        jLabel3.setText("Samuel Ouana");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/images.jpg"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabel5.setText("Calculos rapidos e precisos");

        jLabel6.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabel6.setText("Versao 1.0.0");

        jLabel7.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabel7.setText("UEM");

        jLabel8.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jLabel8.setText("Departamento de Matematica e Informatica");

        file.setText("Calculos");

        jMenuEsfera.setText("Esfera");

        jRaioDoParalelo.setText("Raio do Paralelo");
        jRaioDoParalelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRaioDoParaleloActionPerformed(evt);
            }
        });
        jMenuEsfera.add(jRaioDoParalelo);

        jDistanciaEsferica.setText("Distancia Esferica");
        jDistanciaEsferica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDistanciaEsfericaActionPerformed(evt);
            }
        });
        jMenuEsfera.add(jDistanciaEsferica);

        jMenu1.setText("Conversao de Coordenadas");

        jMenuEsfericasCartesianas.setText("Esfericas para Cartesianas");
        jMenuEsfericasCartesianas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEsfericasCartesianasActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuEsfericasCartesianas);

        jMenuEsfera.add(jMenu1);

        jVelocidadeDeRotacao.setText("Velocidade de Rotacao");
        jVelocidadeDeRotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVelocidadeDeRotacaoActionPerformed(evt);
            }
        });
        jMenuEsfera.add(jVelocidadeDeRotacao);

        file.add(jMenuEsfera);

        jMenuAchatamento.setText("Elipsoide");

        jMenuItem2.setText("Achatamento");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuAchatamento.add(jMenuItem2);

        jMenuExcentricidade.setText("Excentricidade");
        jMenuExcentricidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExcentricidadeActionPerformed(evt);
            }
        });
        jMenuAchatamento.add(jMenuExcentricidade);

        jMenu2.setText("Raios de Curvatura");

        jMenuGrandeNormal.setText("Grande Normal");
        jMenuGrandeNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGrandeNormalActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuGrandeNormal);

        jMenuPequenaNormal.setText("Pequena Normal");
        jMenuPequenaNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPequenaNormalActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuPequenaNormal);

        jMenuSeccaoMeridiana.setText("Seccao Meridiana");
        jMenuSeccaoMeridiana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSeccaoMeridianaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuSeccaoMeridiana);

        jMenuRaioMedio.setText("Raio Medio");
        jMenuRaioMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRaioMedioActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuRaioMedio);

        jMenuAchatamento.add(jMenu2);

        jMenu3.setText("Semi - Eixos");

        lblEixoMaior.setText("Maior");
        lblEixoMaior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblEixoMaiorActionPerformed(evt);
            }
        });
        jMenu3.add(lblEixoMaior);

        lblEixoMenor.setText("Menor");
        lblEixoMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblEixoMenorActionPerformed(evt);
            }
        });
        jMenu3.add(lblEixoMenor);

        jMenuAchatamento.add(jMenu3);

        file.add(jMenuAchatamento);

        jMenuBar1.add(file);

        sair.setText("Opcoes");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        lblSair.setText("Sair");
        lblSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblSairActionPerformed(evt);
            }
        });
        sair.add(lblSair);

        jMenuBar1.add(sair);

        sobre.setText("Sobre");
        sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreActionPerformed(evt);
            }
        });

        jSobre.setText("Sobre");
        jSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSobreActionPerformed(evt);
            }
        });
        sobre.add(jSobre);

        jMenuBar1.add(sobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel7))
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTP)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(32, 32, 32)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTP)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRaioDoParaleloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRaioDoParaleloActionPerformed
        RaioDoParalelo RP = new RaioDoParalelo();
        jTP.add(RP);
        RP.setVisible(true);

    }//GEN-LAST:event_jRaioDoParaleloActionPerformed

    private void jTPAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTPAncestorAdded
       
    }//GEN-LAST:event_jTPAncestorAdded

    private void jMenuEsfericasCartesianasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEsfericasCartesianasActionPerformed
        Conver_Esfericas_Cartesianas CE = new Conver_Esfericas_Cartesianas();
        jTP.add(CE);
        CE.setVisible(true); 
    }//GEN-LAST:event_jMenuEsfericasCartesianasActionPerformed

    private void jVelocidadeDeRotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVelocidadeDeRotacaoActionPerformed
        VelocidadeDeRotacao VP = new VelocidadeDeRotacao();
        jTP.add(VP);
        VP.setVisible(true);
    }//GEN-LAST:event_jVelocidadeDeRotacaoActionPerformed

    private void jDistanciaEsfericaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDistanciaEsfericaActionPerformed
        DistanciaEsferica_A_B DE = new DistanciaEsferica_A_B ();
        jTP.add(DE);
        DE.setVisible (true);
    }//GEN-LAST:event_jDistanciaEsfericaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Achatamento f = new Achatamento();
        jTP.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuExcentricidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExcentricidadeActionPerformed
        Excentricidade e = new Excentricidade ();
        jTP.add(e);
        e.setVisible (true);
    }//GEN-LAST:event_jMenuExcentricidadeActionPerformed

    private void lblEixoMaiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblEixoMaiorActionPerformed
        Semi_Eixos_Maior EM = new Semi_Eixos_Maior ();
        jTP.add(EM);
        EM.setVisible(true);
    }//GEN-LAST:event_lblEixoMaiorActionPerformed

    private void jMenuGrandeNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGrandeNormalActionPerformed
        GrandeNormal RC = new GrandeNormal();
        jTP.add(RC);
        RC.setVisible(true);
    }//GEN-LAST:event_jMenuGrandeNormalActionPerformed

    private void jMenuPequenaNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPequenaNormalActionPerformed
        PequenaNormal PN = new PequenaNormal();
        jTP.add(PN);
        PN.setVisible(true);
    }//GEN-LAST:event_jMenuPequenaNormalActionPerformed

    private void jMenuSeccaoMeridianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSeccaoMeridianaActionPerformed
        SeccaoMeridiana SM = new SeccaoMeridiana();
        jTP.add(SM);
        SM.setVisible(true);
    }//GEN-LAST:event_jMenuSeccaoMeridianaActionPerformed

    private void jMenuRaioMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRaioMedioActionPerformed
        RaioMedio RM = new RaioMedio();
        jTP.add(RM);
        RM.setVisible(true);
        
    }//GEN-LAST:event_jMenuRaioMedioActionPerformed

    private void lblEixoMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblEixoMenorActionPerformed
        Semi_Eixos_Menor EMn = new Semi_Eixos_Menor ();
        jTP.add(EMn);
        EMn.setVisible(true);
    }//GEN-LAST:event_lblEixoMenorActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed

    }//GEN-LAST:event_sairActionPerformed

    private void lblSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblSairActionPerformed
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atencao", JOptionPane.YES_NO_OPTION);
        if(sair == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_lblSairActionPerformed

    private void sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreActionPerformed

        
    }//GEN-LAST:event_sobreActionPerformed

    private void jSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSobreActionPerformed
        Sobre s = new Sobre();
        jTP.add(s);
        s.setVisible(true);
    }//GEN-LAST:event_jSobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu file;
    private javax.swing.JMenuItem jDistanciaEsferica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenuAchatamento;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEsfera;
    private javax.swing.JMenuItem jMenuEsfericasCartesianas;
    private javax.swing.JMenuItem jMenuExcentricidade;
    private javax.swing.JMenuItem jMenuGrandeNormal;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuPequenaNormal;
    private javax.swing.JMenuItem jMenuRaioMedio;
    private javax.swing.JMenuItem jMenuSeccaoMeridiana;
    private javax.swing.JMenuItem jRaioDoParalelo;
    private javax.swing.JMenuItem jSobre;
    private javax.swing.JDesktopPane jTP;
    private javax.swing.JMenuItem jVelocidadeDeRotacao;
    private javax.swing.JMenuItem lblEixoMaior;
    private javax.swing.JMenuItem lblEixoMenor;
    private javax.swing.JMenuItem lblSair;
    private javax.swing.JMenu sair;
    private javax.swing.JMenu sobre;
    // End of variables declaration//GEN-END:variables
}
